title: "Yaman Alazmeh — Portfolio"
description: "Game developer • Unreal Engine • Software Engineer"
baseurl: ""        # leave blank for user site
url: "https://your-username.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Minimal Mistakes settings (basic)
author:
  name: "Yaman Alazmeh"
  avatar: /assets/images/avatar.png
  bio: "Software engineer and game Developer."

navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
    children:
      - title: "Game Dev"
        url: /projects/#game-dev
      - title: "Tools"
        url: /projects/#tools
  - title: "Skills"
    url: /skills/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
  - title: "Resume"
    url: /assets/resume.pdf
    external: true


collections:
  projects:
    output: true
    permalink: /projects/:name/
