title: "Yaman Alazmeh — Portfolio"
description: "Game developer • Unreal Engine • Software Engineer"

url: "https://yaman-alazmeh.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Yaman Alazmeh"
  avatar: "/assets/images/avatar.jpg"
  bio: "Software engineer and game developer."

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: single
